/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-04 08:47:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.room;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class room_005fall_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header_footer/header.jsp", Long.valueOf(1667541996622L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>Shinna Hotel</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"../image/headicon.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Stylesheet -->\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../room/new_css/accommodation.css\" /> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../room/new_css/base.css\"  />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../room/new_css/main.css\" /> \r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../header.css\">\r\n");
      out.write(" </head>\r\n");
      out.write(" <style>\r\n");
      out.write("body, div, td, th, p, textarea {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    \r\n");
      out.write("    color: #101010;\r\n");
      out.write("}\r\n");
      out.write(" </style> \r\n");
      out.write(" <body>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div id=\"preloader\" style=\"background-color: #f1ebd6;\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Preloader -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Area Start -->\r\n");
      out.write("    <header class=\"header-area\">        \r\n");
      out.write("        <!-- Top Header Area Start -->\r\n");
      out.write("        <div class=\"top-header-area\" style=\"background-color: white;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <div class=\"top-header-content\">\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_phone\" style=\"color: #f1e3c4;\"></i> <span>(02) 1234-5678</span></a>\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_mail\" style=\"color: #f1e3c4;\"></i> <span>shinna@hotel.com</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-6\" >\r\n");
      out.write("                        <div class=\"top-header-content\" >\r\n");
      out.write("                            <!-- Top Social Area -->\r\n");
      out.write("                            <div class=\"top-social-area ml-auto\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-tripadvisor\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-instagram\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Top Header Area End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Header Start -->\r\n");
      out.write("        <div class=\"main-header-area\">\r\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\" style=\"background-color: #f1e3c4;\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <!-- Classy Menu -->\r\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"robertoNav\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Logo -->\r\n");
      out.write("                        <a class=\"nav-brand\" href=\"../login/index.jsp\"><img src=\"../image/headerlogo.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navbar Toggler -->\r\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\r\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Menu -->\r\n");
      out.write("                        <div class=\"classy-menu\" >\r\n");
      out.write("                            <!-- Menu Close Button -->\r\n");
      out.write("                            <div class=\"classycloseIcon\">\r\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav Start -->\r\n");
      out.write("                            <div class=\"classynav\">\r\n");
      out.write("                                \r\n");
      out.write("\r\n");
      out.write("                                <!-- Search -->\r\n");
      out.write("                                <div class=\"book-now-btn\"  >\r\n");
      out.write("                                   <a href=\"../room/room_all.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">객실정보</a>|                       \r\n");
      out.write("                                   <a href=\"../inquiry/inquiry.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">문의하기</a>|                          \r\n");
      out.write("                                   <a href=\"../location/location.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">위치찾기</a>|                          \r\n");
      out.write("                                    <a href=\"../reservation/reservation.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">예약 </a>|                              \r\n");
      out.write("                                    <a href=\"../login/login.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">로그인 </a>|\r\n");
      out.write("                                    <a href=\"../join/join.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">회원가입 </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav End -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Area End -->");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <!-- Breadcrumb Area Start -->\r\n");
      out.write("    <div class=\"breadcrumb-area contact-breadcrumb bg-img bg-overlay jarallax\" style=\"background-image: url(img/bg-img/18.jpg);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-content text-center mt-100\">\r\n");
      out.write("                        <h2 class=\"page-title\">객실 정보</h2>\r\n");
      out.write("                        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                            <ol class=\"breadcrumb justify-content-center\">\r\n");
      out.write("                                <li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\" aria-current=\"page\">객실 정보</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Breadcrumb Area End -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"contain\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <!-- temp4 -->\r\n");
      out.write("        <div class=\"lnbArea lnbAreaAcmd\">\r\n");
      out.write("          <div class=\"lnbMenu\">\r\n");
      out.write("            <h2 class=\"tit\">객실</h2>\r\n");
      out.write("            <ul class=\"menu\">\r\n");
      out.write("              <li class=\"m1 first\"><a href=\"room1.jsp\"><span>스탠다드</span></a></li>\r\n");
      out.write("              <li class=\"m2\"><a href=\"\"><span>디럭스</span></a></li>\r\n");
      out.write("              <li class=\"pre_dlx\"><a href=\"\"><span>프리미어 디럭스</span></a></li>\r\n");
      out.write("              <li class=\"m3 last\"><a href=\"\"><span>그랜드</span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <a href=\"\"><span><image src=\"../image/전체객실.png\"> </span></a>\r\n");
      out.write("          </div>          \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"contents\" id=\"contents\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"ctnAcmd ctnallRooms\">\r\n");
      out.write("            <div class=\"location\">\r\n");
      out.write("              <p class=\"list\">\r\n");
      out.write("                <span class=\"crPosit\">현재 페이지 위치 : </span> &gt; 객실 &gt;<strong>전체객실</strong>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"headTit\">\r\n");
      out.write("              <h4 class=\"tit\"><img alt=\"All Rooms\" src=\"https://www.shillastay.com/images/contents/accmo/ACCMO_ALLROOM/R0000000BQ67_KR.gif\"/></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"keepArea\">\r\n");
      out.write("              <a id=\"emailBtn\" href=\"/mapo/accommodation/allRoom.do\">이메일</a>\r\n");
      out.write("              <a id=\"printBtn\" href=\"/mapo/accommodation/allRoom.do\" class=\"print\">인쇄하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 이메일 보내기 -->\r\n");
      out.write("            <div id=\"email\" style=\"display: none\"></div>\r\n");
      out.write("\r\n");
      out.write("            <!-- allroom_info -->\r\n");
      out.write("            <div class=\"allroom_info\">\r\n");
      out.write("              <img src=\"https://www.shillastay.com/images/contents/accmo/ACCMO_ALLROOM/R0000001D9JK_KR.jpg\" alt=\"All Rooms\"/>\r\n");
      out.write("              <div class=\"hidden\">\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- allroom_info end -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- **** All JS Files ***** -->\r\n");
      out.write("    <!-- jQuery 2.2.4 -->\r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper -->\r\n");
      out.write("    <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All Plugins -->\r\n");
      out.write("    <script src=\"../js/roberto.bundle.js\"></script>\r\n");
      out.write("    <!-- Active -->\r\n");
      out.write("    <script src=\"../js/default-assets/active.js\"></script>\r\n");
      out.write("</body> \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
