/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-04 08:48:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.room;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class room1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header_footer/header.jsp", Long.valueOf(1667541996622L));
    _jspx_dependants.put("/header_footer/footer.jsp", Long.valueOf(1667541996621L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>Shinna Hotel</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"../image/headicon.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div id=\"preloader\" style=\"background-color: #f1ebd6;\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Preloader -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Area Start -->\r\n");
      out.write("    <header class=\"header-area\">        \r\n");
      out.write("        <!-- Top Header Area Start -->\r\n");
      out.write("        <div class=\"top-header-area\" style=\"background-color: white;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <div class=\"top-header-content\">\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_phone\" style=\"color: #f1e3c4;\"></i> <span>(02) 1234-5678</span></a>\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_mail\" style=\"color: #f1e3c4;\"></i> <span>shinna@hotel.com</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-6\" >\r\n");
      out.write("                        <div class=\"top-header-content\" >\r\n");
      out.write("                            <!-- Top Social Area -->\r\n");
      out.write("                            <div class=\"top-social-area ml-auto\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-tripadvisor\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-instagram\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Top Header Area End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Header Start -->\r\n");
      out.write("        <div class=\"main-header-area\">\r\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\" style=\"background-color: #f1e3c4;\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <!-- Classy Menu -->\r\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"robertoNav\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Logo -->\r\n");
      out.write("                        <a class=\"nav-brand\" href=\"../login/index.jsp\"><img src=\"../image/headerlogo.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navbar Toggler -->\r\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\r\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Menu -->\r\n");
      out.write("                        <div class=\"classy-menu\" >\r\n");
      out.write("                            <!-- Menu Close Button -->\r\n");
      out.write("                            <div class=\"classycloseIcon\">\r\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav Start -->\r\n");
      out.write("                            <div class=\"classynav\">\r\n");
      out.write("                                \r\n");
      out.write("\r\n");
      out.write("                                <!-- Search -->\r\n");
      out.write("                                <div class=\"book-now-btn\"  >\r\n");
      out.write("                                   <a href=\"../room/room_all.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">객실정보</a>|                       \r\n");
      out.write("                                   <a href=\"../inquiry/inquiry.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">문의하기</a>|                          \r\n");
      out.write("                                   <a href=\"../location/location.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">위치찾기</a>|                          \r\n");
      out.write("                                    <a href=\"../reservation/reservation.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">예약 </a>|                              \r\n");
      out.write("                                    <a href=\"../login/login.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">로그인 </a>|\r\n");
      out.write("                                    <a href=\"../join/join.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">회원가입 </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav End -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Area End -->");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <!-- Breadcrumb Area Start -->\r\n");
      out.write("    <div class=\"breadcrumb-area bg-img bg-overlay jarallax\" style=\"background-image: url(img/bg-img/16.jpg);\">\r\n");
      out.write("        <div class=\"container h-100\">\r\n");
      out.write("            <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-content text-center\">\r\n");
      out.write("                        <h2 class=\"page-title\">객실 정보</h2>\r\n");
      out.write("                        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                            <ol class=\"breadcrumb justify-content-center\">\r\n");
      out.write("                                <li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\" aria-current=\"page\">객실정보</li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\" aria-current=\"page\">스탠다드</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Breadcrumb Area End -->\r\n");
      out.write("<!-- Blog Area Start -->\r\n");
      out.write("    <div class=\"roberto-news-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-12 col-lg-8\">\r\n");
      out.write("                    <!-- Post Thumbnail -->\r\n");
      out.write("                    <div class=\"post-thumbnail mb-50\">\r\n");
      out.write("                        <img src=\"../image/스탠다드1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Blog Details Text -->\r\n");
      out.write("                    <div class=\"blog-details-text\">\r\n");
      out.write("                        <h3>3~16층에 위치한 스탠다드룸은 편안함과 쾌적함이 <br> 인상적인 최상의 휴식 환경을 제공합니다.</h3>\r\n");
      out.write("                        <p>모던한 아름다움과 신나호텔의 고급 침구 및 침대 그리고 고급 어메니티로 <br> 한단계 업그레이드 된 휴식을 경험하십시오.  </p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <p>문의 전화 : <h4>02 - 1234 - 5678</h4> </p>\r\n");
      out.write("\r\n");
      out.write("                        <p>모든 객실과 레스토랑에서 유무선 인터넷 연결이 가능합니다.</p>\r\n");
      out.write("\r\n");
      out.write("                        <p>위치 : 3 ~ 16층 | 전망 : 시티 뷰 | 침대 : 더블, 트윈 | 크기 : 21.7m | 구성 : 침실 1, 욕실 1</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   <!-- Post Author Area -->\r\n");
      out.write("                    <div class=\"post-author-area d-flex align-items-center justify-content-between mb-50\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Author Social Info -->\r\n");
      out.write("                        <div class=\"author-social-info d-flex align-items-center\">\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Comments Area -->\r\n");
      out.write("                    <div class=\"comment_area mb-50 clearfix\">                        \r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <!-- Single Comment Area -->\r\n");
      out.write("                            <li class=\"single_comment_area\">\r\n");
      out.write("                                <!-- Comment Content -->\r\n");
      out.write("                                <div class=\"comment-content d-flex\">\r\n");
      out.write("                                    <!-- Comment Author -->\r\n");
      out.write("                                    <div class=\"comment-author\">\r\n");
      out.write("                                     \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Comment Meta -->\r\n");
      out.write("                                    <div class=\"comment-meta\">\r\n");
      out.write("                                       <table width=\"400\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td colspan=\"2\"></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td rowspan=\"11\" style=\"text-align:left;\">객실이용</td>                                                \r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr><td></td><td>- LED TV</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 책상</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 냉장고</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 무료커피, 티백</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 무료 생수 2병</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 무료 유무선 인터넷</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 개인 금고</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 유니버셜 어댑터</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 다회용 어메니티</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 2개의 목욕가운</td></tr>\r\n");
      out.write("\r\n");
      out.write("                                       </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <div class=\"comment-content d-flex\">\r\n");
      out.write("                                    <!-- Comment Author -->\r\n");
      out.write("                                    <div class=\"comment-author\">\r\n");
      out.write("                                     \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Comment Meta -->\r\n");
      out.write("                                    <div class=\"comment-meta\">\r\n");
      out.write("                                       <table width=\"400\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td colspan=\"2\"></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td rowspan=\"3\" style=\"text-align:left;\">부대시설</td>                                                \r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr><td></td><td>- 피트니스 센터 무료 이용</td></tr>\r\n");
      out.write("                                            <tr><td></td><td>- 비즈니스 코너 인터넷 무료 이용</td></tr>\r\n");
      out.write("                                       </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>                               \r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                          \r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Leave A Reply -->\r\n");
      out.write("                    <div class=\"roberto-contact-form mt-80 mb-100\">\r\n");
      out.write("                        <h2>Leave A Comment</h2>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Form -->\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-sm-8 col-md-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"roberto-sidebar-area pl-md-4\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Newsletter -->\r\n");
      out.write("                        <div class=\"single-widget-area mb-100\">\r\n");
      out.write("                            <div class=\"newsletter-form\">\r\n");
      out.write("                                <h5>객실</h5>\r\n");
      out.write("                                <div style=\"background-color:  #524b42;\" >\r\n");
      out.write("                                    <i class=\"fa fa-arrow-left\" style=\"color: white;\" aria-hidden=\"true\"></i>                                    \r\n");
      out.write("                                    <a href=\"\" style=\"color: white;\" >스탠다드</a>                                    \r\n");
      out.write("                                </div><br>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <a href=\"\">디럭스</a>\r\n");
      out.write("                                </div><br>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <a href=\"\">프리미어 디럭스</a>\r\n");
      out.write("                                </div><br>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <a href=\"\">그랜드</a>\r\n");
      out.write("                                </div><br>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn roberto-btn w-100\"><a href=\"\" style=\"color:white;\">전체 객실 보기</a></button>                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <div style=\"text-align: center;line-height: 50px;\">\r\n");
      out.write("                                <div style=\"display: inline-block;background-color: #524b42;width: 100px; height: 50px;\">\r\n");
      out.write("                                    <a href=\"\" style=\" color: white;\">문의하기</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                &nbsp;&nbsp;\r\n");
      out.write("                                <div style=\"display: inline-block;background-color: #524b42;width: 100px; height: 50px;\">\r\n");
      out.write("                                        <a href=\"\" style=\" color: white;\">예약하기</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("                        <!-- Recent Post -->\r\n");
      out.write("                        <div class=\"single-widget-area mb-100\">\r\n");
      out.write("                            <h4 class=\"widget-title mb-30\">Hotel info.</h4>\r\n");
      out.write("                           \r\n");
      out.write("                            <ul> <h5>체크인/체크아웃시간</h5>\r\n");
      out.write("                                <li>- 체크인 : 오후 3시 이후</li>\r\n");
      out.write("                                <li>- 체크아웃: 정오</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <ul> <h5>주차안내</h5>\r\n");
      out.write("                                <li>- 객실 이용 시 1박당 5,000원</li>\r\n");
      out.write("                                <li>· 객실당 1대</li>\r\n");
      out.write("                                <li>· 차량 추가 시 1박당 15,000원 추가 요금 발생</li>\r\n");
      out.write("                                <li>- 호텔 주차장 만차 시 인근 외부 주차장 이용 </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <ul> <h5>Cafe 이용안내</h5>\r\n");
      out.write("                                <li>- [조식]</li>\r\n");
      out.write("                                <li>(주중) 06:30~09:30</li>\r\n");
      out.write("                                <li>(주말,공휴일) 07:00~10:00</li>\r\n");
      out.write("                                <li>- [중식]</li>\r\n");
      out.write("                                <li>(주중) 11:30~14:00</li>\r\n");
      out.write("                                <li>(주말,공휴일) 12:00~14:30</li>\r\n");
      out.write("                                <li>- [석식]</li>\r\n");
      out.write("                                <li>(주중,주말,공휴일) 18:00~21:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <ul><h5>피트니스 센터 이용안내</h5>\r\n");
      out.write("                                <li>- 06:00 ~ 23:00</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul><h5>예약 변경 및 취소</h5>\r\n");
      out.write("                                <li>- 숙박예정일 1일전 18시까지는 위약금 없이 취소 가능</li>\r\n");
      out.write("                                <li>- 위 기간 이후 취소 또는 변경 시(No Show 포함)</li>\r\n");
      out.write("                                <li>· 성수기(4,5,6,10,11월, 12/24, 12/31) : 최초 1박 요금의 80% 부과</li>\r\n");
      out.write("                                <li>· 비수기(성수기 외 기간) : 최초 1박 요금의 10% 부과</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- Popular Tags -->\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Blog Area End -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!-- Footer Area Start -->\r\n");
      out.write("    <footer class=\"footer-area section-padding-80-0\">\r\n");
      out.write("        <!-- Main Footer Area -->\r\n");
      out.write("        <div class=\"main-footer-area\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-baseline justify-content-between\">\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                        	<a href=\"index.jsp\">\r\n");
      out.write("                        		<image src=\"../image/푸터.png\">\r\n");
      out.write("                        	</a>\r\n");
      out.write("<!--                             Footer Logo -->\r\n");
      out.write("<!--                             <a href=\"#\" class=\"footer-logo\"><img src=\"img/core-img/logo2.png\" alt=\"\"></a> -->\r\n");
      out.write("\r\n");
      out.write("<!--                             <h4>+12 345-678-9999</h4> -->\r\n");
      out.write("<!--                             <span>Info.colorlib@gmail.com</span> -->\r\n");
      out.write("<!--                             <span>856 Cordia Extension Apt. 356, Lake Deangeloburgh, South Africa</span> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                            <!-- Widget Title -->\r\n");
      out.write("                            <h5 class=\"widget-title\" style=\"color: black; \" >신나호텔</h5>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Single Blog Area -->\r\n");
      out.write("                            <div class=\"latest-blog-area\">\r\n");
      out.write("                                <a href=\"#\" class=\"post-title\">서울 강남구 테헤란로 146</a>\r\n");
      out.write("                                <span class=\"post-date\">역삼동 736-6</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Single Blog Area -->\r\n");
      out.write("                            <div class=\"latest-blog-area\">\r\n");
      out.write("                                <a href=\"#\" class=\"post-title\">02) 1234 - 5678 </a>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-4 col-lg-2\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                            <!-- Widget Title -->\r\n");
      out.write("                            <h5 class=\"widget-title\"></h5>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Footer Nav -->\r\n");
      out.write("                            <ul class=\"footer-nav\" style=\"color: #524b42;\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 소개</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 객실정보</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 예약</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 문의하기</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Copywrite Area -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"copywrite-content\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-12 col-md-8\">\r\n");
      out.write("                        <!-- Copywrite Text -->\r\n");
      out.write("                        <div class=\"copywrite-text\">\r\n");
      out.write("                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | 신라호텔 사이트를 모티브로 제작된 사이트입니다.\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-md-4\">\r\n");
      out.write("                        <!-- Social Info -->\r\n");
      out.write("                        <div class=\"social-info\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Area End -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- **** All JS Files ***** -->\r\n");
      out.write("    <!-- jQuery 2.2.4 -->\r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper -->\r\n");
      out.write("    <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All Plugins -->\r\n");
      out.write("    <script src=\"../js/roberto.bundle.js\"></script>\r\n");
      out.write("    <!-- Active -->\r\n");
      out.write("    <script src=\"../js/default-assets/active.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
