/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-11 10:19:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reservationlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/seulk/Desktop/jsp4_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shinnaHotel/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1667373596000L));
    _jspx_dependants.put("/header_footer/header.jsp", Long.valueOf(1668043830000L));
    _jspx_dependants.put("/header_footer/footer.jsp", Long.valueOf(1667896758000L));
    _jspx_dependants.put("jar:file:/C:/Users/seulk/Desktop/jsp4_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shinnaHotel/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>Shinna Hotel - 예약 내역</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"../image/headicon.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
String u_id = (String)session.getAttribute("u_id");
    String login = "";
    if (u_id != null ){
    	login = "<a href= /reservation/ReservationSelect.re    style=background-color:#f1e3c4;color:#524b42;>내 정보 </a>|";	
    } else{
    	login = "<a href=../login/login.jsp style=background-color:#f1e3c4;color:#524b42;>로그인 </a>|";
    }
    
    String join = "";
    if (u_id != null ){
    	join = "<a href=../login/logout.jsp style=background-color:#f1e3c4;color:#524b42;>로그아웃</a>";	
    } else{
    	join = "<a href=../join/join.jsp style=background-color:#f1e3c4;color:#524b42;>회원가입 </a>";
    }
    
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div id=\"preloader\" style=\"background-color: #f1ebd6;\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Preloader -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Area Start -->\r\n");
      out.write("    <header class=\"header-area\">        \r\n");
      out.write("        <!-- Top Header Area Start -->\r\n");
      out.write("        <div class=\"top-header-area\" style=\"background-color: white;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <div class=\"top-header-content\">\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_phone\" style=\"color: #f1e3c4;\"></i> <span>(02) 1234-5678</span></a>\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_mail\" style=\"color: #f1e3c4;\"></i> <span>shinna@hotel.com</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-6\" >\r\n");
      out.write("                        <div class=\"top-header-content\" >\r\n");
      out.write("                            <!-- Top Social Area -->\r\n");
      out.write("                            <div class=\"top-social-area ml-auto\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-tripadvisor\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-instagram\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Top Header Area End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Header Start -->\r\n");
      out.write("        <div class=\"main-header-area\">\r\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\" style=\"background-color: #f1e3c4;\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <!-- Classy Menu -->\r\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"robertoNav\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Logo -->\r\n");
      out.write("                        <a class=\"nav-brand\" href=\"../login/index.jsp\"><img src=\"../image/headerlogo.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navbar Toggler -->\r\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\r\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Menu -->\r\n");
      out.write("                        <div class=\"classy-menu\" >\r\n");
      out.write("                            <!-- Menu Close Button -->\r\n");
      out.write("                            <div class=\"classycloseIcon\">\r\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav Start -->\r\n");
      out.write("                            <div class=\"classynav\">\r\n");
      out.write("                                \r\n");
      out.write("\r\n");
      out.write("                                <!-- Search -->\r\n");
      out.write("                                <div class=\"book-now-btn\"  >\r\n");
      out.write("                                   <a href=\"../room/room_all.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">객실정보</a>|                       \r\n");
      out.write("                                   <a href=\"../inquiry/inquiry.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">문의하기</a>|                          \r\n");
      out.write("                                   <a href=\"../location/location.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">위치찾기</a>|                          \r\n");
      out.write("                                    <a href=\"../reservation/reservation.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">예약 </a>|                              \r\n");
      out.write("                                    ");
      out.print(login );
      out.write("\r\n");
      out.write("                                    ");
      out.print(join );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav End -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Area End -->");
      out.write("\r\n");
      out.write(" 	");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"breadcrumb-area bg-img bg-overlay jarallax\" style=\"background-image: url(../image/R0000001PC6L_KR.jpg);\">\r\n");
      out.write("        <div class=\"container h-100\">\r\n");
      out.write("            <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-content text-center\">\r\n");
      out.write("                        <h2 class=\"page-title\">예약 내역</h2>\r\n");
      out.write("                        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                            <ol class=\"breadcrumb justify-content-center\">\r\n");
      out.write("                                <li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\" aria-current=\"page\">내 정보</li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\" aria-current=\"page\">예약내역</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    <div class=\"roberto-news-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("            	\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-sm-8 col-md-6 col-lg-3\">\r\n");
      out.write("                    <div class=\"roberto-sidebar-area pl-md-4\">\r\n");
      out.write("                        <div class=\"single-widget-area mb-100\">\r\n");
      out.write("                            <div class=\"newsletter-form\">\r\n");
      out.write("                                <h4 style=\"margin-bottom: 30px;font-weight: bold\">내 정보</h4>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <a href=\"../mypage/myinfo.jsp\" >내 정보 관리</a>                                    \r\n");
      out.write("                                </div><br>\r\n");
      out.write("                                <div style=\"background-color:#524b42;text-align: center;\" >\r\n");
      out.write("                                    <a href=\"../reservation/reservationlist.jsp\" style=\"color: white;\">예약 내역</a>\r\n");
      out.write("                                </div>                               \r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("		        </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-8\">\r\n");
      out.write("                    \r\n");
      out.write("                    <h2 style=\"text-align: center;height: 50px;\"><span style=\"background-color: #524b42;color: white;padding: 10px;\">예약 내역</span></h2>\r\n");
      out.write("                    <div class=\"post-thumbnail mb-50\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <table class=\"col-12\" style=\"text-align: center;\">\r\n");
      out.write("                                <thead style=\"background-color: #f1e3c4;height: 70px;border-top: #524b42;\" >                            \r\n");
      out.write("                                    <th>예약번호</th>\r\n");
      out.write("                                    <th>성인</th>\r\n");
      out.write("                                    <th>어린이</th>\r\n");
      out.write("                                    <th>체크인</th>\r\n");
      out.write("                                    <th>체크아웃</th>\r\n");
      out.write("                                    <th>객실</th>\r\n");
      out.write("                                    <th>금액</th>                                    \r\n");
      out.write("                                    <th>예약일</th>\r\n");
      out.write("                                    <th>취소</th>                                \r\n");
      out.write("                                </thead>                                \r\n");
      out.write("                                <tbody>\r\n");
      out.write("\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                </tbody>\r\n");
      out.write("                    \r\n");
      out.write("                                                               \r\n");
      out.write("                            </table>\r\n");
      out.write("                            <hr>\r\n");
      out.write("						<div style=\"text-align: center; line-height: 50px;\">\r\n");
      out.write("								<div style=\"display: inline-block; background-color: #524b42; width: 100px; height: 50px;\">\r\n");
      out.write("									<a href=\"../index.jsp\" style=\"color: white;\">확인</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"comment_area mb-50 clearfix\">                        \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                   \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!-- Footer Area Start -->\r\n");
      out.write("    <footer class=\"footer-area section-padding-80-0\">\r\n");
      out.write("        <!-- Main Footer Area -->\r\n");
      out.write("        <div class=\"main-footer-area\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-baseline justify-content-between\">\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                        	<a href=\"index.jsp\">\r\n");
      out.write("                        		<image src=\"../image/푸터.png\">\r\n");
      out.write("                        	</a>\r\n");
      out.write("<!--                             Footer Logo -->\r\n");
      out.write("<!--                             <a href=\"#\" class=\"footer-logo\"><img src=\"img/core-img/logo2.png\" alt=\"\"></a> -->\r\n");
      out.write("\r\n");
      out.write("<!--                             <h4>+12 345-678-9999</h4> -->\r\n");
      out.write("<!--                             <span>Info.colorlib@gmail.com</span> -->\r\n");
      out.write("<!--                             <span>856 Cordia Extension Apt. 356, Lake Deangeloburgh, South Africa</span> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                            <!-- Widget Title -->\r\n");
      out.write("                            <h5 class=\"widget-title\" style=\"color: black; \" >신나호텔</h5>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Single Blog Area -->\r\n");
      out.write("                            <div class=\"latest-blog-area\">\r\n");
      out.write("                                <a href=\"#\" class=\"post-title\">서울 강남구 테헤란로 146</a>\r\n");
      out.write("                                <span class=\"post-date\">역삼동 736-6</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Single Blog Area -->\r\n");
      out.write("                            <div class=\"latest-blog-area\">\r\n");
      out.write("                                <a href=\"#\" class=\"post-title\">02) 1234 - 5678 </a>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-4 col-lg-2\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                            <!-- Widget Title -->\r\n");
      out.write("                            <h5 class=\"widget-title\"></h5>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Footer Nav -->\r\n");
      out.write("                            <ul class=\"footer-nav\" style=\"color: #524b42;\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 소개</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 객실정보</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 예약</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 문의하기</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Copywrite Area -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"copywrite-content\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-12 col-md-8\">\r\n");
      out.write("                        <!-- Copywrite Text -->\r\n");
      out.write("                        <div class=\"copywrite-text\">\r\n");
      out.write("                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | 신라호텔 사이트를 모티브로 제작된 사이트입니다.\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-md-4\">\r\n");
      out.write("                        <!-- Social Info -->\r\n");
      out.write("                        <div class=\"social-info\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Area End -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"../js/roberto.bundle.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"../js/default-assets/active.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    	function cancelCheck() {\r\n");
      out.write("			alert(\"취소하시겠습니까??\");\r\n");
      out.write("		}\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /reservation/reservationlist.jsp(21,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("reservationlist");
      // /reservation/reservationlist.jsp(21,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.reservationlist }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	                                    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /reservation/reservationlist.jsp(87,37) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationlist != null and fn:length(reservationlist) > 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			                                 ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	                                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /reservation/reservationlist.jsp(88,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("reservation");
      // /reservation/reservationlist.jsp(88,36) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationlist }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				                                    <tr style=\"height: 40px;\">\r\n");
            out.write("					                                    <form action=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/reservation/ReservationCancel.re?res_number=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_number }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&res_price=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&res_checkin=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_checkin }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&res_checkout=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_checkout }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&res_rtype=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_rtype }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" method=\"POST\">\r\n");
            out.write("					                                        <td name=\"res_number\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_number }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_adults }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_kids }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td name=\"res_checkin\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_checkin }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td name=\"res_checkout\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_checkout }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td name=\"res_rtype\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_rtype }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td name=\"res_price\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservation.res_time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                                        <td><button type='submit' style=\"margin-left:5px;margin-right: 5px;width:auto;background-color: #524b42;color: white;border:0px;padding:5px;padding-left:10px;padding-right:10px;\" onclick=\"cancelCheck()\">예약 취소</button></td>\r\n");
            out.write("					                                   </form>\r\n");
            out.write("				                                    </tr>\r\n");
            out.write("			                                  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                          <tr style=\"height: 40px;\">\r\n");
          out.write("                                             <td colspan=\"9\" style=\"text-align: center; font-size:20px; color: #524b42;\">예약 내역이 없습니다.</td>\r\n");
          out.write("                                          </tr>\r\n");
          out.write("                                       ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
