/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-11 10:18:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;

public final class reservationcheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/seulk/Desktop/jsp4_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shinnaHotel/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1667373596000L));
    _jspx_dependants.put("/header_footer/header.jsp", Long.valueOf(1668043830000L));
    _jspx_dependants.put("/header_footer/footer.jsp", Long.valueOf(1667896758000L));
    _jspx_dependants.put("jar:file:/C:/Users/seulk/Desktop/jsp4_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shinnaHotel/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int r_price = Integer.parseInt(request.getParameter("r_price"));
String r_type = request.getParameter("r_type");
String r_id = request.getParameter("r_id");
int diffday = Integer.parseInt(request.getParameter("diffday"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>Shinna Hotel</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"../image/headicon.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
String u_id = (String)session.getAttribute("u_id");
    String login = "";
    if (u_id != null ){
    	login = "<a href= /reservation/ReservationSelect.re    style=background-color:#f1e3c4;color:#524b42;>내 정보 </a>|";	
    } else{
    	login = "<a href=../login/login.jsp style=background-color:#f1e3c4;color:#524b42;>로그인 </a>|";
    }
    
    String join = "";
    if (u_id != null ){
    	join = "<a href=../login/logout.jsp style=background-color:#f1e3c4;color:#524b42;>로그아웃</a>";	
    } else{
    	join = "<a href=../join/join.jsp style=background-color:#f1e3c4;color:#524b42;>회원가입 </a>";
    }
    
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div id=\"preloader\" style=\"background-color: #f1ebd6;\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Preloader -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Area Start -->\r\n");
      out.write("    <header class=\"header-area\">        \r\n");
      out.write("        <!-- Top Header Area Start -->\r\n");
      out.write("        <div class=\"top-header-area\" style=\"background-color: white;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <div class=\"top-header-content\">\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_phone\" style=\"color: #f1e3c4;\"></i> <span>(02) 1234-5678</span></a>\r\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_mail\" style=\"color: #f1e3c4;\"></i> <span>shinna@hotel.com</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-6\" >\r\n");
      out.write("                        <div class=\"top-header-content\" >\r\n");
      out.write("                            <!-- Top Social Area -->\r\n");
      out.write("                            <div class=\"top-social-area ml-auto\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-tripadvisor\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-instagram\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Top Header Area End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Header Start -->\r\n");
      out.write("        <div class=\"main-header-area\">\r\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\" style=\"background-color: #f1e3c4;\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <!-- Classy Menu -->\r\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"robertoNav\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Logo -->\r\n");
      out.write("                        <a class=\"nav-brand\" href=\"../login/index.jsp\"><img src=\"../image/headerlogo.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navbar Toggler -->\r\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\r\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Menu -->\r\n");
      out.write("                        <div class=\"classy-menu\" >\r\n");
      out.write("                            <!-- Menu Close Button -->\r\n");
      out.write("                            <div class=\"classycloseIcon\">\r\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav Start -->\r\n");
      out.write("                            <div class=\"classynav\">\r\n");
      out.write("                                \r\n");
      out.write("\r\n");
      out.write("                                <!-- Search -->\r\n");
      out.write("                                <div class=\"book-now-btn\"  >\r\n");
      out.write("                                   <a href=\"../room/room_all.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">객실정보</a>|                       \r\n");
      out.write("                                   <a href=\"../inquiry/inquiry.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">문의하기</a>|                          \r\n");
      out.write("                                   <a href=\"../location/location.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">위치찾기</a>|                          \r\n");
      out.write("                                    <a href=\"../reservation/reservation.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">예약 </a>|                              \r\n");
      out.write("                                    ");
      out.print(login );
      out.write("\r\n");
      out.write("                                    ");
      out.print(join );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav End -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Area End -->");
      out.write("\r\n");
      out.write("     ");
 session = request.getSession(); 
      out.write("\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <!-- Breadcrumb Area Start -->\r\n");
      out.write("    <div class=\"breadcrumb-area contact-breadcrumb bg-img bg-overlay jarallax\" style=\"background-image: url(../image/그랜드1.jpg);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-content text-center mt-100\">\r\n");
      out.write("                        <h2 class=\"page-title\">예약하기</h2>\r\n");
      out.write("                        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                            <ol class=\"breadcrumb justify-content-center\">\r\n");
      out.write("                                <li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\" aria-current=\"page\">예약하기</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Breadcrumb Area End -->\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("    <section class=\"roberto-about-area section-padding-100-0\">\r\n");
      out.write("        <!-- Hotel Search Form Area -->\r\n");
      out.write("        <div class=\"hotel-search-form-area\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"hotel-search-form\">\r\n");
      out.write("                    <form action=\"#\" method=\"post\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <!-- Section Heading -->\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"section-heading text-center wow fadeInUp\" data-wow-delay=\"100ms\">\r\n");
      out.write("                                    <h6 style=\"color: #524b42;\">Shinna</h6>\r\n");
      out.write("                                    <h2 style=\"color: #524b42;\"> 결제 확인</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("           \r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </section>\r\n");
      out.write("	\r\n");
      out.write("           <!-- Blog Area Start -->\r\n");
      out.write("<form name=\"paymentform\" onsubmit=\"return doSubmit();\"  action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservation/DoReservation.re\" method=\"GET\">\r\n");
      out.write("        \r\n");
      out.write("    <section class=\"roberto-blog-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("          <div class=\"col2 colR\" >\r\n");
      out.write("            <div class=\"cont\" style=\"text-align:center\">\r\n");
      out.write("                <div class=\"fmTitWrap mt0\" style=\"text-align:center\">\r\n");
      out.write("                    <strong class=\"fmTit\">신용카드 정보</strong> <!-- 로그인 한 고객 노출 -->\r\n");
      out.write("                    </div><br>\r\n");
      out.write("\r\n");
      out.write("                <table class=\"customerInfo\" style=\"border-spacing: 30px;border: 1px;\">\r\n");
      out.write("                    <colgroup>\r\n");
      out.write("                        <col style=\"width: 450px;\">\r\n");
      out.write("                        <col style=\"width: auto;\">\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr style=\"width: 100px;height: 50px; \">\r\n");
      out.write("                            <th scope=\"row\">\r\n");
      out.write("                                카드종류<em class=\"necessary\">\r\n");
      out.write("                                </em>\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <div class=\"optionList\" style=\"text-align:center\">\r\n");
      out.write("                                    <div class=\"selectWrap4\" style=\"text-align:center\">\r\n");
      out.write("                                        <select title=\"카드종류 선택\" id=\"guestCardTypCd\" name=\"guestCardTypCd\" >\r\n");
      out.write("                                            <option value=\"\">선택</option>\r\n");
      out.write("                                                    <option value=\"AX\" >AMEX CARD</option>\r\n");
      out.write("                                                    <option value=\"BC\" >BC CARD</option>\r\n");
      out.write("                                                    <option value=\"CB\" >CITIBANK CARD</option>\r\n");
      out.write("                                                    <option value=\"DI\" >DINERS CARD</option>\r\n");
      out.write("                                                    <option value=\"HD\" >HYUNDAI CARD</option>\r\n");
      out.write("                                                    <option value=\"JC\" >JCB CARD</option>\r\n");
      out.write("                                                    <option value=\"KE\" >KEB CARD</option>\r\n");
      out.write("                                                    <option value=\"KM\" >KOOKMIN CARD</option>\r\n");
      out.write("                                                    <option value=\"LO\" >LOTTE CARD</option>\r\n");
      out.write("                                                    <option value=\"MA\" >MASTER OVERSEAS</option>\r\n");
      out.write("                                                    <option value=\"SH\" >SHINHAN CARD</option>\r\n");
      out.write("                                                    <option value=\"SS\" >SAMSUNG CARD</option>\r\n");
      out.write("                                                    <option value=\"VS\" >VISA OVERSEAS</option>\r\n");
      out.write("                                                    <option value=\"UN\" >UNION PAY</option>\r\n");
      out.write("                                                    </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr style=\"width: 100px;height: 50px; \">\r\n");
      out.write("                            <th scope=\"row\">\r\n");
      out.write("                                카드번호<em class=\"necessary\">\r\n");
      out.write("                                </em>\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <div class=\"optionList\">\r\n");
      out.write("                                     <input type=\"text\" id=\"cardNo1\" class=\"text textResv\" title=\"카드번호 첫번째 네 자리 입력\" style=\"width: 71px;\" maxlength=\"4\" onkeyup=\"this.value=this.value.replace(/[^\\d\\ ]/g, '');\" name=\"cardnumber\">\r\n");
      out.write("                                    	<span class=\"hyphen\">-</span>\r\n");
      out.write("              						<input type=\"password\" id=\"cardNo2\" class=\"text textResv\" title=\"카드번호 두번쨰 네 자리 입력\" style=\"width: 71px\" maxlength=\"4\" onkeyup=\"this.value=this.value.replace(/[^\\d\\ ]/g, '');\" name=\"cardnumber1\">\r\n");
      out.write("                                    	<span class=\"hyphen\">-</span>\r\n");
      out.write("                                    <input type=\"password\" id=\"cardNo3\" class=\"text textResv\" title=\"카드번호 세번쨰 네 자리 입력\" style=\"width: 71px\" maxlength=\"4\" onkeyup=\"this.value=this.value.replace(/[^\\d\\ ]/g, '');\" name=\"cardnumber2\">\r\n");
      out.write("                                    	<span class=\"hyphen\">-</span>\r\n");
      out.write("                                    <input type=\"password\" id=\"cardNo4\" class=\"text textResv last\" title=\"카드번호 마지막 네 자리 입력\" style=\"width: 71px\" maxlength=\"4\" onkeyup=\"this.value=this.value.replace(/[^\\d\\ ]/g, '');\" name=\"cardnumber3\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr style=\"width: 100px;height: 50px; \">\r\n");
      out.write("                            <th scope=\"row\">\r\n");
      out.write("                                유효기간<em class=\"necessary\">\r\n");
      out.write("                                </em>\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                    <div class=\"optionList\">\r\n");
      out.write("                                        <div style=\"float:left\"><select id=\"cardExprMonth\" name=\"cardExprMonth\" class=\"endDayMonth uiform\" title=\"월 선택\">\r\n");
      out.write("                                            <option value=\"\">월</option>\r\n");
      out.write("                                            <option value=\"01\">01</option>\r\n");
      out.write("                                            <option value=\"02\">02</option>\r\n");
      out.write("                                            <option value=\"03\">03</option>\r\n");
      out.write("                                            <option value=\"04\">04</option>\r\n");
      out.write("                                            <option value=\"05\">05</option>\r\n");
      out.write("                                            <option value=\"06\">06</option>\r\n");
      out.write("                                            <option value=\"07\">07</option>\r\n");
      out.write("                                            <option value=\"08\">08</option>\r\n");
      out.write("                                            <option value=\"09\">09</option>\r\n");
      out.write("                                            <option value=\"10\">10</option>\r\n");
      out.write("                                            <option value=\"11\">11</option>\r\n");
      out.write("                                            <option value=\"12\">12</option>\r\n");
      out.write("                                            </select></div>\r\n");
      out.write("                                   \r\n");
      out.write("                                            <div style=\"float:left;margin-left: 10px;\"><select id=\"cardExprYear\" name=\"cardExprYear\" class=\"endDayYear uiform\" title=\"년 선택\">\r\n");
      out.write("                                            <span style=\"width: 100px; user-select: none;\"></span>\r\n");
      out.write("                                            <option value=\"\">년</option>\r\n");
      out.write("                                            <option value=\"2032\" >2032</option>\r\n");
      out.write("                                            <option value=\"2031\" >2031</option>\r\n");
      out.write("                                            <option value=\"2030\" >2030</option>\r\n");
      out.write("                                            <option value=\"2029\" >2029</option>\r\n");
      out.write("                                            <option value=\"2028\" >2028</option>\r\n");
      out.write("                                            <option value=\"2027\" >2027</option>\r\n");
      out.write("                                            <option value=\"2026\" >2026</option>\r\n");
      out.write("                                            <option value=\"2025\" >2025</option>\r\n");
      out.write("                                            <option value=\"2024\" >2024</option>\r\n");
      out.write("                                            <option value=\"2023\" >2023</option>\r\n");
      out.write("                                            <option value=\"2022\" >2022</option>\r\n");
      out.write("                                            </select></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table><br><br>\r\n");
      out.write("                <ul class=\"notiList1\">\r\n");
      out.write("                    <li>신용카드 정보는 고객님의 투숙을 개런티하기 위한 용도 외에는 어떤 목적으로도</li> \r\n");
      out.write("                    <li>사용되지 않으며, 체크카드 및 일부 신용 카드의 경우 사용이 제한 될 수 있습니다.</li>\r\n");
      out.write("                            <li><em class=\"pointColor1\">온라인 예약 시 직접 결제가 이루어지지 않으며,</em> 최종 결제는 프론트 데스크에서 해주시기 바랍니다.</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("        <!-- //colR -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr style=\"border: solid 1px black;\">\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"container\" style=\"float:center;\">\r\n");
      out.write("                               \r\n");
      out.write("                        <div class=\"select-wrap\">\r\n");
      out.write("                            <div style=\"text-align: center;line-height: 50px;\">\r\n");
      out.write("                                <div style=\"display: inline-block;background-color: #524b42;width: 100px; height: 50px;\" >\r\n");
      out.write("                                    <a  href=\"\" style=\" color: white; margin-left: 10px;margin-right: 10px;\">< 문의하기</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                &nbsp;&nbsp;\r\n");
      out.write("                       \r\n");
      out.write("                                <div style=\"display: inline-block;background-color: #524b42;width: auto; height: 50px;\">\r\n");
      out.write("                                        <a href=\"\" style=\" color: white; margin-left: 10px;margin-right: 10px;\">결제 금액 : </a><a href=\"\" style=\" color: white; margin-left: 10px;margin-right: 10px;\"> ");
      out.print(r_price * diffday );
      out.write(" 원</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                               \r\n");
      out.write("                                &nbsp;&nbsp;\r\n");
      out.write("                                <div style=\"display: inline-block;background-color: #524b42;width: 100px; height: 50px;\">\r\n");
      out.write("                              ");
      out.write("\r\n");
      out.write("                                              <input type=\"hidden\" name=\"checkin_date\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkin_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"checkout_date\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkout_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"room\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"adults\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adults }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"children\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${children }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"r_price\"  value=\"");
      out.print(r_price );
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"r_type\"  value=\"");
      out.print(r_type );
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"r_id\"  value=\"");
      out.print(r_id );
      out.write("\">\r\n");
      out.write("                                              <input type=\"hidden\" name=\"diffday\"  value=\"");
      out.print(diffday );
      out.write("\">\r\n");
      out.write("                                              <button type=\"submit\" style=\"display: inline;color: white;background-color: #524b42; margin-left: ;margin-right: ;border:0;\">예약하기 ></button>\r\n");
      out.write("\r\n");
      out.write("                               ");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div> <br><br><br>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write(" </form>        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     		\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!-- Footer Area Start -->\r\n");
      out.write("    <footer class=\"footer-area section-padding-80-0\">\r\n");
      out.write("        <!-- Main Footer Area -->\r\n");
      out.write("        <div class=\"main-footer-area\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-baseline justify-content-between\">\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                        	<a href=\"index.jsp\">\r\n");
      out.write("                        		<image src=\"../image/푸터.png\">\r\n");
      out.write("                        	</a>\r\n");
      out.write("<!--                             Footer Logo -->\r\n");
      out.write("<!--                             <a href=\"#\" class=\"footer-logo\"><img src=\"img/core-img/logo2.png\" alt=\"\"></a> -->\r\n");
      out.write("\r\n");
      out.write("<!--                             <h4>+12 345-678-9999</h4> -->\r\n");
      out.write("<!--                             <span>Info.colorlib@gmail.com</span> -->\r\n");
      out.write("<!--                             <span>856 Cordia Extension Apt. 356, Lake Deangeloburgh, South Africa</span> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                            <!-- Widget Title -->\r\n");
      out.write("                            <h5 class=\"widget-title\" style=\"color: black; \" >신나호텔</h5>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Single Blog Area -->\r\n");
      out.write("                            <div class=\"latest-blog-area\">\r\n");
      out.write("                                <a href=\"#\" class=\"post-title\">서울 강남구 테헤란로 146</a>\r\n");
      out.write("                                <span class=\"post-date\">역삼동 736-6</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Single Blog Area -->\r\n");
      out.write("                            <div class=\"latest-blog-area\">\r\n");
      out.write("                                <a href=\"#\" class=\"post-title\">02) 1234 - 5678 </a>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-4 col-lg-2\">\r\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\r\n");
      out.write("                            <!-- Widget Title -->\r\n");
      out.write("                            <h5 class=\"widget-title\"></h5>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Footer Nav -->\r\n");
      out.write("                            <ul class=\"footer-nav\" style=\"color: #524b42;\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 소개</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 객실정보</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 예약</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 문의하기</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Footer Widget Area -->\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Copywrite Area -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"copywrite-content\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-12 col-md-8\">\r\n");
      out.write("                        <!-- Copywrite Text -->\r\n");
      out.write("                        <div class=\"copywrite-text\">\r\n");
      out.write("                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | 신라호텔 사이트를 모티브로 제작된 사이트입니다.\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-md-4\">\r\n");
      out.write("                        <!-- Social Info -->\r\n");
      out.write("                        <div class=\"social-info\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Area End -->");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write(" <script>\r\n");
      out.write("	function doSubmit(){\r\n");
      out.write("		// 폼 객체\r\n");
      out.write("		let frm = document.paymentform;\r\n");
      out.write("		\r\n");
      out.write("		// 카드 종류 선택\r\n");
      out.write("		if(frm.guestCardTypCd.selectedIndex < 1){\r\n");
      out.write("			alert(\"카드 종류를 선택해 주세요\");\r\n");
      out.write("			\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 카드 번호 입력\r\n");
      out.write("		if(frm.cardnumber.value.length == 0 ||\r\n");
      out.write("			frm.cardnumber1.value.length == 0 ||\r\n");
      out.write("			frm.cardnumber2.value.length == 0 ||\r\n");
      out.write("			frm.cardnumber3.value.length == 0	){\r\n");
      out.write("			alert('카드 번호를 입력해 주세요.');\r\n");
      out.write("\r\n");
      out.write("			return false;\r\n");
      out.write("		} \r\n");
      out.write("\r\n");
      out.write("		// 카드 유효기간		\r\n");
      out.write("		if(frm.cardExprMonth.selectedIndex < 1){\r\n");
      out.write("			alert(\"카드 유효기간을 선택해 주세요\");\r\n");
      out.write("			\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(frm.cardExprYear.selectedIndex < 1){\r\n");
      out.write("			alert(\"카드 유효기간을 선택해 주세요\");\r\n");
      out.write("			\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("    <!-- **** All JS Files ***** -->\r\n");
      out.write("    <!-- jQuery 2.2.4 -->\r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper -->\r\n");
      out.write("    <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All Plugins -->\r\n");
      out.write("    <script src=\"../js/roberto.bundle.js\"></script>\r\n");
      out.write("    <!-- Active -->\r\n");
      out.write("    <script src=\"../js/default-assets/active.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /reservation/reservationcheck.jsp(38,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("checkin_date");
      // /reservation/reservationcheck.jsp(38,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.checkin_date}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /reservation/reservationcheck.jsp(39,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("checkout_date");
      // /reservation/reservationcheck.jsp(39,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.checkout_date}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /reservation/reservationcheck.jsp(40,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("room");
      // /reservation/reservationcheck.jsp(40,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.room}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /reservation/reservationcheck.jsp(41,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("adults");
      // /reservation/reservationcheck.jsp(41,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.adults}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /reservation/reservationcheck.jsp(42,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("children");
      // /reservation/reservationcheck.jsp(42,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.children}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }
}
